# Generated by Django 6.0.3 on 2026-03-04 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='contact_email',
            new_name='email',
        ),
    ]
